import type { TableColumn } from "@nuxt/ui";
import type { Driver } from "~/types/driver";
import type { Zone } from "~/types/zone";

export const summary = ref({
	active: 18,
	at_plant: 12,
	returning_30: 3,
	returning_2hr: 12,
	requirement_30: 22,
	requirement_2hr: 32,
	inactive: 0,
});

const overlay = useOverlay();

export const zoneColumn: TableColumn<Zone>[] = [
	{
		accessorKey: "zone",
		header: "Zone",
		footer: ({}) => {
			return h("strong", {}, "Total");
		},
	},
	{
		accessorKey: "active",
		header: "Active",
		footer: ({}) => {
			return h("strong", {}, summary.value.active);
		},
	},
	{
		accessorKey: "at_plant",
		header: "At Plant",
		footer: ({}) => {
			return h("strong", {}, summary.value.at_plant);
		},
	},
	{
		accessorKey: "return_30min",
		header: () =>
			h("div", { class: "text-center" }, [
				"Returning",
				h("div", { class: "text-xs text-gray-500" }, "[≤ 30 mins]"),
			]),
		footer: ({}) => {
			return h("strong", {}, summary.value.returning_30);
		},
	},
	{
		accessorKey: "requirement_30",
		header: () =>
			h("div", { class: "text-center" }, [
				"Required",
				h("div", { class: "text-xs text-gray-500" }, "[≤ 30 mins]"),
			]),
		footer: ({}) => {
			return h("strong", {}, summary.value.requirement_30);
		},
	},
	{
		accessorKey: "excess_shortage_30min",
		header: () =>
			h("div", { class: "text-center" }, [
				"Excess / Shortage",
				h("div", { class: "text-xs text-gray-500" }, "[≤ 30 mins]"),
			]),
		cell: ({ row }) => {
			const atPlant = row.getValue("at_plant") as number;
			const return30min = row.getValue("return_30min") as number;
			const requirement30 = row.getValue("requirement_30") as number;
			const excessShortage = atPlant + return30min - requirement30;
			return h("span", {}, excessShortage > 0 ? `+${excessShortage}` : `${excessShortage}`);
		},
		footer: ({}) => {
			return h(
				"strong",
				{},
				summary.value.at_plant + summary.value.returning_30 - summary.value.requirement_30
			);
		},
	},
	{
		accessorKey: "return_aft_30min",
		header: () =>
			h("div", { class: "text-center" }, [
				"Returning Plant",
				h("div", { class: "text-xs text-gray-500" }, "[> 30 mins]"),
			]),
		footer: ({}) => {
			return h("strong", {}, summary.value.returning_2hr - summary.value.returning_30);
		},
	},

	{
		accessorKey: "requirement_aft_30",
		header: () =>
			h("div", { class: "text-center" }, [
				"Required",
				h("div", { class: "text-xs text-gray-500" }, "[> 30 mins]"),
			]),
		footer: ({}) => {
			return h("strong", {}, summary.value.requirement_2hr - summary.value.requirement_30);
		},
	},
	{
		accessorKey: "excess_shortage_aft_30min",
		header: () =>
			h("div", { class: "text-center" }, [
				"Excess / Shortage",
				h("div", { class: "text-xs text-gray-500" }, "[> 30 mins]"),
			]),
		cell: ({ row }) => {
			const atPlant = row.getValue("at_plant") as number;
			const return30min = row.getValue("return_30min") as number;
			const requirement30 = row.getValue("requirement_30") as number;
			const returnAft30min = row.getValue("return_aft_30min") as number;
			const requirementAft30 = row.getValue("requirement_aft_30") as number;
			const excessShortage =
				atPlant + return30min + returnAft30min - (requirement30 + requirementAft30);

			return h("span", {}, excessShortage > 0 ? `+${excessShortage}` : `${excessShortage}`);
		},
		footer: ({}) => {
			return h(
				"strong",
				{},
				summary.value.at_plant + summary.value.returning_2hr - summary.value.requirement_2hr
			);
		},
	},
	{
		accessorKey: "inactive",
		header: "Inactive",
		footer: ({}) => {
			return h("strong", {}, summary.value.inactive);
		},
	},
];

export const driverInfoColumns: TableColumn<Driver>[] = [
	{ accessorKey: "name", header: "Driver Name" },
	{ accessorKey: "truck_no", header: "Truck No." },
	{ accessorKey: "phone", header: "Mobile No." },
	{ accessorKey: "status", header: " Current Status" },
	{ accessorKey: "trips", header: "No. of Loads Today" },
];

export const zoneRequirement = ref<Zone[]>([
	{
		zone: "North",
		requirement_30: 15,
		requirement_aft_30: 20,
		active: 0,
		inactive: 0,
		at_plant: 0,
		return_30min: 0,
		return_aft_30min: 0,
		excess_shortage_30min: 0,
		excess_shortage_aft_30min: 0,
	},
	{
		zone: "South",
		requirement_30: 4,
		requirement_aft_30: 12,
		active: 0,
		inactive: 0,
		at_plant: 0,
		return_30min: 0,
		return_aft_30min: 0,
		excess_shortage_30min: 0,
		excess_shortage_aft_30min: 0,
	},
	{
		zone: "East",
		requirement_30: 12,
		requirement_aft_30: 19,
		active: 0,
		inactive: 0,
		at_plant: 0,
		return_30min: 0,
		return_aft_30min: 0,
		excess_shortage_30min: 0,
		excess_shortage_aft_30min: 0,
	},
	{
		zone: "West",
		requirement_30: 12,
		requirement_aft_30: 18,
		active: 0,
		inactive: 0,
		at_plant: 0,
		return_30min: 0,
		return_aft_30min: 0,
		excess_shortage_30min: 0,
		excess_shortage_aft_30min: 0,
	},
]);

export const driver_full_data: Driver[] = [
	{
		name: "Jacob Smith",
		active: "Active",
		zone: "North",
		status: "At Plant",
		phone: 93269150,
		trips: 4,
		truck_no: 923,
	},
	{
		name: "Samuel Johnson",
		active: "Active",
		zone: "North",
		status: "At Plant",
		phone: 91870913,
		trips: 3,
		truck_no: 819,
	},
	{
		name: "Alexander Brown",
		active: "Active",
		zone: "North",
		status: "Returning [≤30mins]",
		phone: 94213562,
		trips: 5,
		truck_no: 916,
	},
	{
		name: "Matthew Davis",
		active: "Active",
		zone: "North",
		status: "Returning [≤30mins]",
		phone: 95360535,
		trips: 5,
		truck_no: 280,
	},
	{
		name: "Benjamin Wilson",
		active: "Active",
		zone: "North",
		status: "Returning [≤30mins]",
		phone: 95165239,
		trips: 4,
		truck_no: 744,
	},
	{
		name: "James Taylor",
		active: "Active",
		zone: "North",
		status: "Returning [≤30mins]",
		phone: 96779401,
		trips: 5,
		truck_no: 544,
	},
	{
		name: "Daniel Martinez",
		active: "Active",
		zone: "North",
		status: "Returning [≤30mins]",
		phone: 91762354,
		trips: 3,
		truck_no: 236,
	},
	{
		name: "Joseph Anderson",
		active: "Active",
		zone: "North",
		status: "Returning [≤30mins]",
		phone: 96665239,
		trips: 4,
		truck_no: 225,
	},
	{
		name: "Michael Thomas",
		active: "Active",
		zone: "North",
		status: "Returning [≤30mins]",
		phone: 98254102,
		trips: 5,
		truck_no: 595,
	},
	{
		name: "David Jackson",
		active: "Active",
		zone: "North",
		status: "Returning [≤30mins]",
		phone: 99135390,
		trips: 4,
		truck_no: 656,
	},
	{
		name: "Ethan White",
		active: "Active",
		zone: "North",
		status: "Returning [≤30mins]",
		phone: 90092120,
		trips: 4,
		truck_no: 641,
	},
	{
		name: "Christopher Harris",
		active: "Active",
		zone: "North",
		status: "Returning [≤30mins]",
		phone: 93880303,
		trips: 3,
		truck_no: 605,
	},
	{
		name: "Ryan Martin",
		active: "Active",
		zone: "North",
		status: "Returning [>30mins]",
		phone: 91716908,
		trips: 4,
		truck_no: 154,
	},
	{
		name: "John Thompson",
		active: "Active",
		zone: "North",
		status: "Returning [>30mins]",
		phone: 90251027,
		trips: 5,
		truck_no: 658,
	},
	{
		name: "Nicholas Garcia",
		active: "Active",
		zone: "North",
		status: "Returning [>30mins]",
		phone: 99643459,
		trips: 3,
		truck_no: 162,
	},
	{
		name: "William Martinez",
		active: "Active",
		zone: "North",
		status: "Returning [>30mins]",
		phone: 95494961,
		trips: 4,
		truck_no: 397,
	},
	{
		name: "Andrew Robinson",
		active: "Active",
		zone: "North",
		status: "Returning [>30mins]",
		phone: 98365218,
		trips: 5,
		truck_no: 621,
	},
	{
		name: "Jonathan Clark",
		active: "Active",
		zone: "North",
		status: "Returning [>30mins]",
		phone: 97727679,
		trips: 3,
		truck_no: 691,
	},
	{
		name: "Joshua Rodriguez",
		active: "Active",
		zone: "North",
		status: "Returning [>30mins]",
		phone: 93896959,
		trips: 4,
		truck_no: 686,
	},
	{
		name: "Anthony Lewis",
		active: "Active",
		zone: "North",
		status: "Returning [>30mins]",
		phone: 92151400,
		trips: 5,
		truck_no: 311,
	},
	{
		name: "Brandon Lee",
		active: "Active",
		zone: "North",
		status: "Returning [>30mins]",
		phone: 98334457,
		trips: 4,
		truck_no: 392,
	},
	{
		name: "Tyler Walker",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 99051299,
		trips: 4,
		truck_no: 914,
	},
	{
		name: "Logan Hall",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 97229372,
		trips: 3,
		truck_no: 464,
	},
	{
		name: "Christopher Young",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 95774663,
		trips: 4,
		truck_no: 885,
	},
	{
		name: "Zachary King",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 96576319,
		trips: 3,
		truck_no: 489,
	},
	{
		name: "Kevin Wright",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 97451780,
		trips: 5,
		truck_no: 963,
	},
	{
		name: "Steven Scott",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 98574736,
		trips: 3,
		truck_no: 909,
	},
	{
		name: "Brian Adams",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 94144013,
		trips: 5,
		truck_no: 763,
	},
	{
		name: "Timothy Mitchell",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 99047513,
		trips: 5,
		truck_no: 635,
	},
	{
		name: "Jacob Hill",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 93729301,
		trips: 3,
		truck_no: 454,
	},
	{
		name: "Jeffrey Green",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 90666568,
		trips: 4,
		truck_no: 988,
	},
	{
		name: "Justin Baker",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 98702878,
		trips: 5,
		truck_no: 996,
	},
	{
		name: "Austin Gonzalez",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 95602557,
		trips: 4,
		truck_no: 817,
	},
	{
		name: "Alexander Nelson",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 92988451,
		trips: 3,
		truck_no: 710,
	},
	{
		name: "Nicholas Carter",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 92318505,
		trips: 4,
		truck_no: 792,
	},
	{
		name: "Jeremy Wood",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 94485905,
		trips: 4,
		truck_no: 217,
	},
	{
		name: "Christian Ramirez",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 98351664,
		trips: 4,
		truck_no: 154,
	},
	{
		name: "Gabriel Turner",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 92128984,
		trips: 4,
		truck_no: 355,
	},
	{
		name: "Jonathan Phillips",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 92766259,
		trips: 4,
		truck_no: 301,
	},
	{
		name: "Elijah Evans",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 93247675,
		trips: 4,
		truck_no: 114,
	},
	{
		name: "Caleb Perry",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 91367482,
		trips: 5,
		truck_no: 505,
	},
	{
		name: "Dylan Morris",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 96983034,
		trips: 4,
		truck_no: 384,
	},
	{
		name: "Isaac Cook",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 98795161,
		trips: 3,
		truck_no: 232,
	},
	{
		name: "Jameson Bailey",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 98360070,
		trips: 4,
		truck_no: 572,
	},
	{
		name: "Jeremiah Ward",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 98359234,
		trips: 5,
		truck_no: 603,
	},
	{
		name: "Nathaniel Bell",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 97394574,
		trips: 4,
		truck_no: 796,
	},
	{
		name: "Dominic Murphy",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 95202691,
		trips: 5,
		truck_no: 987,
	},
	{
		name: "Luke Rivera",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 93663163,
		trips: 3,
		truck_no: 392,
	},
	{
		name: "Sebastian Torres",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 97938910,
		trips: 4,
		truck_no: 999,
	},
	{
		name: "Adam Reed",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 96336525,
		trips: 5,
		truck_no: 594,
	},
	{
		name: "Julian Collins",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 98248389,
		trips: 5,
		truck_no: 990,
	},
	{
		name: "Chase Ward",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 98916131,
		trips: 3,
		truck_no: 392,
	},
	{
		name: "Carter Reed",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 97832809,
		trips: 3,
		truck_no: 643,
	},
	{
		name: "Blake Price",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 95417856,
		trips: 5,
		truck_no: 152,
	},
	{
		name: "Brayden Mitchell",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 91272055,
		trips: 5,
		truck_no: 916,
	},
	{
		name: "Jayden Stewart",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 93256498,
		trips: 5,
		truck_no: 464,
	},
	{
		name: "Connor Jenkins",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 95921682,
		trips: 4,
		truck_no: 392,
	},
	{
		name: "Grayson Turner",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 93359968,
		trips: 3,
		truck_no: 905,
	},
	{
		name: "Hunter Hernandez",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 92307635,
		trips: 5,
		truck_no: 683,
	},
	{
		name: "Miles Scott",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 93317155,
		trips: 3,
		truck_no: 775,
	},
	{
		name: "Cole Patterson",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 92167826,
		trips: 4,
		truck_no: 550,
	},
	{
		name: "Carson Powell",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 95193029,
		trips: 5,
		truck_no: 983,
	},
	{
		name: "Cooper Perry",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 91796952,
		trips: 3,
		truck_no: 116,
	},
	{
		name: "Parker Hughes",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 99882642,
		trips: 5,
		truck_no: 531,
	},
	{
		name: "Wyatt Carter",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 93453815,
		trips: 4,
		truck_no: 602,
	},
	{
		name: "Jordan Bennett",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 95031693,
		trips: 4,
		truck_no: 686,
	},
	{
		name: "Henry Hayes",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 93690298,
		trips: 5,
		truck_no: 212,
	},
	{
		name: "Jason Kim",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 96608101,
		trips: 5,
		truck_no: 767,
	},
	{
		name: "Kai Perry",
		active: "Active",
		zone: "North",
		status: "Ongoing Delivery",
		phone: 90402704,
		trips: 5,
		truck_no: 448,
	},
	{
		name: "Leo Alexander",
		active: "Active",
		zone: "South",
		status: "At Plant",
		phone: 96250951,
		trips: 3,
		truck_no: 204,
	},
	{
		name: "Max Simmons",
		active: "Active",
		zone: "South",
		status: "At Plant",
		phone: 91377137,
		trips: 4,
		truck_no: 364,
	},
	{
		name: "Oscar Foster",
		active: "Active",
		zone: "South",
		status: "Returning [≤30mins]",
		phone: 97944239,
		trips: 4,
		truck_no: 733,
	},
	{
		name: "Patrick Griffin",
		active: "Active",
		zone: "South",
		status: "Returning [≤30mins]",
		phone: 99957863,
		trips: 5,
		truck_no: 232,
	},
	{
		name: "Robert Bell",
		active: "Active",
		zone: "South",
		status: "Returning [≤30mins]",
		phone: 96558309,
		trips: 3,
		truck_no: 760,
	},
	{
		name: "Seth Barnes",
		active: "Active",
		zone: "South",
		status: "Returning [≤30mins]",
		phone: 97371288,
		trips: 5,
		truck_no: 776,
	},
	{
		name: "Xavier Dixon",
		active: "Active",
		zone: "South",
		status: "Returning [≤30mins]",
		phone: 98129468,
		trips: 4,
		truck_no: 557,
	},
	{
		name: "Adrian Campbell",
		active: "Active",
		zone: "South",
		status: "Returning [>30mins]",
		phone: 90624358,
		trips: 3,
		truck_no: 326,
	},
	{
		name: "Dominic Thompson",
		active: "Active",
		zone: "South",
		status: "Returning [>30mins]",
		phone: 91341754,
		trips: 5,
		truck_no: 913,
	},
	{
		name: "Ian Mitchell",
		active: "Active",
		zone: "South",
		status: "Returning [>30mins]",
		phone: 97296266,
		trips: 4,
		truck_no: 869,
	},
	{
		name: "Zachary Clarke",
		active: "Active",
		zone: "South",
		status: "Returning [>30mins]",
		phone: 93851166,
		trips: 4,
		truck_no: 112,
	},
	{
		name: "Blake Collins",
		active: "Active",
		zone: "South",
		status: "Returning [>30mins]",
		phone: 92356577,
		trips: 4,
		truck_no: 314,
	},
	{
		name: "Derek Stevens",
		active: "Active",
		zone: "South",
		status: "Returning [>30mins]",
		phone: 97292064,
		trips: 4,
		truck_no: 873,
	},
	{
		name: "Edward Watson",
		active: "Active",
		zone: "South",
		status: "Returning [>30mins]",
		phone: 96733574,
		trips: 3,
		truck_no: 867,
	},
	{
		name: "Fernando Rivera",
		active: "Active",
		zone: "South",
		status: "Returning [>30mins]",
		phone: 95935922,
		trips: 3,
		truck_no: 597,
	},
	{
		name: "Gavin Reed",
		active: "Active",
		zone: "South",
		status: "Returning [>30mins]",
		phone: 90150513,
		trips: 4,
		truck_no: 329,
	},
	{
		name: "Hector Griffin",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 98362482,
		trips: 5,
		truck_no: 142,
	},
	{
		name: "Ivan Perry",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 94578076,
		trips: 3,
		truck_no: 681,
	},
	{
		name: "Juan Murphy",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 99151269,
		trips: 4,
		truck_no: 154,
	},
	{
		name: "Keith Sanchez",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 98856681,
		trips: 4,
		truck_no: 881,
	},
	{
		name: "Leonardo Parker",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 99639496,
		trips: 5,
		truck_no: 156,
	},
	{
		name: "Marco Ramirez",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 94587637,
		trips: 5,
		truck_no: 495,
	},
	{
		name: "Nolan Ward",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 98632984,
		trips: 3,
		truck_no: 416,
	},
	{
		name: "Oliver Butler",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 94579317,
		trips: 4,
		truck_no: 381,
	},
	{
		name: "Peter Price",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 99952490,
		trips: 5,
		truck_no: 895,
	},
	{
		name: "Quinn Jenkins",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 92774646,
		trips: 5,
		truck_no: 959,
	},
	{
		name: "Ricardo Murphy",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 96891901,
		trips: 5,
		truck_no: 197,
	},
	{
		name: "Simon Ross",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 97187325,
		trips: 3,
		truck_no: 115,
	},
	{
		name: "Tanner Hayes",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 97085071,
		trips: 4,
		truck_no: 491,
	},
	{
		name: "Uriel Alexander",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 91207475,
		trips: 5,
		truck_no: 803,
	},
	{
		name: "Victor Lopez",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 91369174,
		trips: 3,
		truck_no: 871,
	},
	{
		name: "Wesley Turner",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 97134885,
		trips: 3,
		truck_no: 266,
	},
	{
		name: "Xavier Perez",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 95657893,
		trips: 3,
		truck_no: 457,
	},
	{
		name: "Yahir Collins",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 92464053,
		trips: 3,
		truck_no: 669,
	},
	{
		name: "Zane Carter",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 90514795,
		trips: 4,
		truck_no: 915,
	},
	{
		name: "Abel Hayes",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 95264913,
		trips: 5,
		truck_no: 694,
	},
	{
		name: "Bryant Hughes",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 95846021,
		trips: 4,
		truck_no: 388,
	},
	{
		name: "Caleb Stewart",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 99876306,
		trips: 3,
		truck_no: 259,
	},
	{
		name: "Darius Price",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 93651951,
		trips: 5,
		truck_no: 494,
	},
	{
		name: "Ethan Richardson",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 99037113,
		trips: 4,
		truck_no: 449,
	},
	{
		name: "Felix Watson",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 93853317,
		trips: 5,
		truck_no: 540,
	},
	{
		name: "Garrett Bell",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 98265356,
		trips: 3,
		truck_no: 947,
	},
	{
		name: "Hayden Powell",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 91081467,
		trips: 3,
		truck_no: 561,
	},
	{
		name: "Isaiah Edwards",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 98048774,
		trips: 5,
		truck_no: 170,
	},
	{
		name: "Jaden Perry",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 98148463,
		trips: 5,
		truck_no: 122,
	},
	{
		name: "Kyle Lopez",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 96776882,
		trips: 4,
		truck_no: 822,
	},
	{
		name: "Liam Hayes",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 93808715,
		trips: 5,
		truck_no: 909,
	},
	{
		name: "Marcus Dixon",
		active: "Active",
		zone: "South",
		status: "Ongoing Delivery",
		phone: 97398634,
		trips: 5,
		truck_no: 808,
	},
	{
		name: "Nathan Stewart",
		active: "Active",
		zone: "East",
		status: "At Plant",
		phone: 90702356,
		trips: 3,
		truck_no: 457,
	},
	{
		name: "Owen Clarke",
		active: "Active",
		zone: "East",
		status: "At Plant",
		phone: 90232331,
		trips: 5,
		truck_no: 604,
	},
	{
		name: "Parker Ross",
		active: "Active",
		zone: "East",
		status: "At Plant",
		phone: 94756351,
		trips: 3,
		truck_no: 846,
	},
	{
		name: "Quinton Murphy",
		active: "Active",
		zone: "East",
		status: "At Plant",
		phone: 98168085,
		trips: 5,
		truck_no: 700,
	},
	{
		name: "Ricardo Campbell",
		active: "Active",
		zone: "East",
		status: "At Plant",
		phone: 93484325,
		trips: 3,
		truck_no: 251,
	},
	{
		name: "Santiago Perry",
		active: "Active",
		zone: "East",
		status: "At Plant",
		phone: 91077401,
		trips: 4,
		truck_no: 820,
	},
	{
		name: "Theodore Simmons",
		active: "Active",
		zone: "East",
		status: "At Plant",
		phone: 90333139,
		trips: 4,
		truck_no: 285,
	},
	{
		name: "Uriah Ross",
		active: "Active",
		zone: "East",
		status: "At Plant",
		phone: 98941234,
		trips: 3,
		truck_no: 646,
	},
	{
		name: "Victor Jenkins",
		active: "Active",
		zone: "East",
		status: "At Plant",
		phone: 92414685,
		trips: 4,
		truck_no: 910,
	},
	{
		name: "Wesley Butler",
		active: "Active",
		zone: "East",
		status: "At Plant",
		phone: 91054207,
		trips: 3,
		truck_no: 638,
	},
	{
		name: "Xavier Murphy",
		active: "Active",
		zone: "East",
		status: "At Plant",
		phone: 91760902,
		trips: 3,
		truck_no: 305,
	},
	{
		name: "Yahir Collins",
		active: "Active",
		zone: "East",
		status: "Returning [≤30mins]",
		phone: 97321634,
		trips: 5,
		truck_no: 968,
	},
	{
		name: "Zander Parker",
		active: "Active",
		zone: "East",
		status: "Returning [≤30mins]",
		phone: 97388760,
		trips: 5,
		truck_no: 763,
	},
	{
		name: "Andrew White",
		active: "Active",
		zone: "East",
		status: "Returning [≤30mins]",
		phone: 97736878,
		trips: 5,
		truck_no: 438,
	},
	{
		name: "Benjamin Martinez",
		active: "Active",
		zone: "East",
		status: "Returning [≤30mins]",
		phone: 90259905,
		trips: 4,
		truck_no: 749,
	},
	{
		name: "Caleb Johnson",
		active: "Active",
		zone: "East",
		status: "Returning [≤30mins]",
		phone: 92717606,
		trips: 4,
		truck_no: 609,
	},
	{
		name: "David Clark",
		active: "Active",
		zone: "East",
		status: "Returning [≤30mins]",
		phone: 92920379,
		trips: 3,
		truck_no: 175,
	},
	{
		name: "Elijah Wilson",
		active: "Active",
		zone: "East",
		status: "Returning [>30mins]",
		phone: 96114254,
		trips: 3,
		truck_no: 853,
	},
	{
		name: "Frank Edwards",
		active: "Active",
		zone: "East",
		status: "Returning [>30mins]",
		phone: 91981909,
		trips: 4,
		truck_no: 135,
	},
	{
		name: "Gabriel Wright",
		active: "Active",
		zone: "East",
		status: "Returning [>30mins]",
		phone: 93884346,
		trips: 5,
		truck_no: 518,
	},
	{
		name: "Henry Green",
		active: "Active",
		zone: "East",
		status: "Returning [>30mins]",
		phone: 91712408,
		trips: 5,
		truck_no: 127,
	},
	{
		name: "Ian Turner",
		active: "Active",
		zone: "East",
		status: "Returning [>30mins]",
		phone: 93644979,
		trips: 5,
		truck_no: 226,
	},
	{
		name: "Julian Rodriguez",
		active: "Active",
		zone: "East",
		status: "Returning [>30mins]",
		phone: 95475367,
		trips: 5,
		truck_no: 587,
	},
	{
		name: "Kevin Bell",
		active: "Active",
		zone: "East",
		status: "Returning [>30mins]",
		phone: 97805829,
		trips: 5,
		truck_no: 859,
	},
	{
		name: "Liam Patterson",
		active: "Active",
		zone: "East",
		status: "Returning [>30mins]",
		phone: 93662178,
		trips: 3,
		truck_no: 230,
	},
	{
		name: "Mason Foster",
		active: "Active",
		zone: "East",
		status: "Returning [>30mins]",
		phone: 90493804,
		trips: 3,
		truck_no: 531,
	},
	{
		name: "Nathan Cook",
		active: "Active",
		zone: "East",
		status: "Returning [>30mins]",
		phone: 94603684,
		trips: 4,
		truck_no: 119,
	},
	{
		name: "Oscar Murphy",
		active: "Active",
		zone: "East",
		status: "Ongoing Delivery",
		phone: 98052135,
		trips: 4,
		truck_no: 367,
	},
	{
		name: "Peter Hayes",
		active: "Active",
		zone: "East",
		status: "Ongoing Delivery",
		phone: 93671530,
		trips: 4,
		truck_no: 703,
	},
	{
		name: "Quinn Campbell",
		active: "Active",
		zone: "East",
		status: "Ongoing Delivery",
		phone: 98217434,
		trips: 5,
		truck_no: 197,
	},
	{
		name: "Ryan Alexander",
		active: "Active",
		zone: "East",
		status: "Ongoing Delivery",
		phone: 93335374,
		trips: 3,
		truck_no: 569,
	},
	{
		name: "Samuel Carter",
		active: "Active",
		zone: "East",
		status: "Ongoing Delivery",
		phone: 99302345,
		trips: 5,
		truck_no: 410,
	},
	{
		name: "Thomas Stewart",
		active: "Active",
		zone: "East",
		status: "Ongoing Delivery",
		phone: 97326968,
		trips: 3,
		truck_no: 882,
	},
	{
		name: "Uriel Watson",
		active: "Active",
		zone: "East",
		status: "Ongoing Delivery",
		phone: 90608645,
		trips: 5,
		truck_no: 519,
	},
	{
		name: "Vincent Perez",
		active: "Active",
		zone: "East",
		status: "Ongoing Delivery",
		phone: 97023371,
		trips: 4,
		truck_no: 669,
	},
	{
		name: "Wesley Price",
		active: "Active",
		zone: "East",
		status: "Ongoing Delivery",
		phone: 91262392,
		trips: 3,
		truck_no: 210,
	},
	{
		name: "Xavier Richardson",
		active: "Active",
		zone: "East",
		status: "Ongoing Delivery",
		phone: 96451784,
		trips: 3,
		truck_no: 708,
	},
	{
		name: "Yahir Rivera",
		active: "Active",
		zone: "East",
		status: "Ongoing Delivery",
		phone: 93782103,
		trips: 3,
		truck_no: 338,
	},
	{
		name: "Zachary Butler",
		active: "Active",
		zone: "East",
		status: "Ongoing Delivery",
		phone: 92279441,
		trips: 3,
		truck_no: 299,
	},
	{
		name: "Aidan Campbell",
		active: "Active",
		zone: "East",
		status: "Ongoing Delivery",
		phone: 95612319,
		trips: 4,
		truck_no: 206,
	},
	{
		name: "Brandon Perry",
		active: "Active",
		zone: "East",
		status: "Ongoing Delivery",
		phone: 91413838,
		trips: 3,
		truck_no: 991,
	},
	{
		name: "Caleb Turner",
		active: "Active",
		zone: "East",
		status: "Ongoing Delivery",
		phone: 97645034,
		trips: 3,
		truck_no: 709,
	},
	{
		name: "Dominic Ross",
		active: "Active",
		zone: "East",
		status: "Ongoing Delivery",
		phone: 99809104,
		trips: 5,
		truck_no: 414,
	},
	{
		name: "Ethan Murphy",
		active: "Active",
		zone: "West",
		status: "At Plant",
		phone: 98966487,
		trips: 4,
		truck_no: 455,
	},
	{
		name: "Fernando Collins",
		active: "Active",
		zone: "West",
		status: "At Plant",
		phone: 95011348,
		trips: 5,
		truck_no: 797,
	},
	{
		name: "Gabriel Parker",
		active: "Active",
		zone: "West",
		status: "At Plant",
		phone: 93831101,
		trips: 5,
		truck_no: 826,
	},
	{
		name: "Hector Jenkins",
		active: "Active",
		zone: "West",
		status: "At Plant",
		phone: 97992906,
		trips: 3,
		truck_no: 166,
	},
	{
		name: "Ivan Martinez",
		active: "Active",
		zone: "West",
		status: "At Plant",
		phone: 91596026,
		trips: 5,
		truck_no: 309,
	},
	{
		name: "Jacob Clark",
		active: "Active",
		zone: "West",
		status: "At Plant",
		phone: 90006348,
		trips: 3,
		truck_no: 594,
	},
	{
		name: "Kyle Wilson",
		active: "Active",
		zone: "West",
		status: "At Plant",
		phone: 98770203,
		trips: 4,
		truck_no: 963,
	},
	{
		name: "Liam Edwards",
		active: "Active",
		zone: "West",
		status: "At Plant",
		phone: 90334312,
		trips: 4,
		truck_no: 358,
	},
	{
		name: "Marcus Wright",
		active: "Active",
		zone: "West",
		status: "At Plant",
		phone: 97024489,
		trips: 4,
		truck_no: 229,
	},
	{
		name: "Nathan Green",
		active: "Active",
		zone: "West",
		status: "At Plant",
		phone: 99075796,
		trips: 4,
		truck_no: 822,
	},
	{
		name: "Oliver Turner",
		active: "Active",
		zone: "West",
		status: "At Plant",
		phone: 98782580,
		trips: 5,
		truck_no: 145,
	},
	{
		name: "Parker Rodriguez",
		active: "Active",
		zone: "West",
		status: "At Plant",
		phone: 95811463,
		trips: 5,
		truck_no: 144,
	},
	{
		name: "Quinn Hayes",
		active: "Active",
		zone: "West",
		status: "At Plant",
		phone: 96387570,
		trips: 3,
		truck_no: 412,
	},
	{
		name: "Ricardo Foster",
		active: "Active",
		zone: "West",
		status: "At Plant",
		phone: 90093600,
		trips: 3,
		truck_no: 240,
	},
	{
		name: "Santiago Murphy",
		active: "Active",
		zone: "West",
		status: "At Plant",
		phone: 96486233,
		trips: 5,
		truck_no: 738,
	},
	{
		name: "Theodore Hayes",
		active: "Active",
		zone: "West",
		status: "Returning [≤30mins]",
		phone: 96733201,
		trips: 5,
		truck_no: 846,
	},
	{
		name: "Uriah Simmons",
		active: "Active",
		zone: "West",
		status: "Returning [≤30mins]",
		phone: 95647162,
		trips: 5,
		truck_no: 597,
	},
	{
		name: "Victor Ross",
		active: "Active",
		zone: "West",
		status: "Returning [≤30mins]",
		phone: 94537815,
		trips: 3,
		truck_no: 783,
	},
	{
		name: "Wesley Murphy",
		active: "Active",
		zone: "West",
		status: "Returning [>30mins]",
		phone: 97142188,
		trips: 4,
		truck_no: 266,
	},
	{
		name: "Xavier Butler",
		active: "Active",
		zone: "West",
		status: "Returning [>30mins]",
		phone: 96410799,
		trips: 4,
		truck_no: 539,
	},
	{
		name: "Yahir Campbell",
		active: "Active",
		zone: "West",
		status: "Returning [>30mins]",
		phone: 91330575,
		trips: 5,
		truck_no: 793,
	},
	{
		name: "Zachary Perry",
		active: "Active",
		zone: "West",
		status: "Returning [>30mins]",
		phone: 98846457,
		trips: 5,
		truck_no: 963,
	},
	{
		name: "Aidan Turner",
		active: "Active",
		zone: "West",
		status: "Returning [>30mins]",
		phone: 92847888,
		trips: 3,
		truck_no: 654,
	},
	{
		name: "Brandon Ross",
		active: "Active",
		zone: "West",
		status: "Returning [>30mins]",
		phone: 98293810,
		trips: 4,
		truck_no: 840,
	},
	{
		name: "Caleb Watson",
		active: "Active",
		zone: "West",
		status: "Returning [>30mins]",
		phone: 96914346,
		trips: 5,
		truck_no: 314,
	},
	{
		name: "Dominic Perez",
		active: "Active",
		zone: "West",
		status: "Returning [>30mins]",
		phone: 96033843,
		trips: 5,
		truck_no: 743,
	},
	{
		name: "Ethan Richardson",
		active: "Active",
		zone: "West",
		status: "Returning [>30mins]",
		phone: 94366833,
		trips: 5,
		truck_no: 632,
	},
	{
		name: "Fernando Stewart",
		active: "Active",
		zone: "West",
		status: "Returning [>30mins]",
		phone: 92499788,
		trips: 5,
		truck_no: 885,
	},
	{
		name: "Gabriel Rivera",
		active: "Active",
		zone: "West",
		status: "Returning [>30mins]",
		phone: 97338753,
		trips: 3,
		truck_no: 148,
	},
	{
		name: "Hector Hayes",
		active: "Active",
		zone: "West",
		status: "Returning [>30mins]",
		phone: 95973154,
		trips: 4,
		truck_no: 251,
	},
	{
		name: "Ivan Turner",
		active: "Active",
		zone: "West",
		status: "Returning [>30mins]",
		phone: 96146145,
		trips: 4,
		truck_no: 638,
	},
	{
		name: "Jacob Richardson",
		active: "Active",
		zone: "West",
		status: "Returning [>30mins]",
		phone: 97741643,
		trips: 3,
		truck_no: 448,
	},
	{
		name: "Kyle Jenkins",
		active: "Active",
		zone: "West",
		status: "Returning [>30mins]",
		phone: 96244573,
		trips: 5,
		truck_no: 857,
	},
	{
		name: "Liam Martinez",
		active: "Active",
		zone: "West",
		status: "Returning [>30mins]",
		phone: 92880618,
		trips: 3,
		truck_no: 413,
	},
	{
		name: "Marcus Clark",
		active: "Active",
		zone: "West",
		status: "Returning [>30mins]",
		phone: 93534809,
		trips: 3,
		truck_no: 679,
	},
	{
		name: "Nathan Wilson",
		active: "Active",
		zone: "West",
		status: "Returning [>30mins]",
		phone: 94488085,
		trips: 5,
		truck_no: 174,
	},
	{
		name: "Oliver Edwards",
		active: "Active",
		zone: "West",
		status: "Returning [>30mins]",
		phone: 97502516,
		trips: 5,
		truck_no: 135,
	},
	{
		name: "Parker Wright",
		active: "Active",
		zone: "West",
		status: "Returning [>30mins]",
		phone: 98116406,
		trips: 5,
		truck_no: 281,
	},
	{
		name: "Quinn Foster",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 91910482,
		trips: 5,
		truck_no: 274,
	},
	{
		name: "Ricardo Collins",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 94486674,
		trips: 5,
		truck_no: 791,
	},
	{
		name: "Santiago Parker",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 91442421,
		trips: 5,
		truck_no: 539,
	},
	{
		name: "Theodore Jenkins",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 98809550,
		trips: 4,
		truck_no: 411,
	},
	{
		name: "Uriah Martinez",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 99843094,
		trips: 4,
		truck_no: 279,
	},
	{
		name: "Victor Turner",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 97077450,
		trips: 3,
		truck_no: 246,
	},
	{
		name: "Wesley Richardson",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 98022565,
		trips: 4,
		truck_no: 829,
	},
	{
		name: "Xavier Stewart",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 94373039,
		trips: 4,
		truck_no: 937,
	},
	{
		name: "Yahir Murphy",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 98937763,
		trips: 5,
		truck_no: 371,
	},
	{
		name: "Zachary Butler",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 90141707,
		trips: 3,
		truck_no: 532,
	},
	{
		name: "Aidan Perry",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 93165609,
		trips: 5,
		truck_no: 576,
	},
	{
		name: "Brandon Turner",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 90145344,
		trips: 5,
		truck_no: 603,
	},
	{
		name: "Caleb Watson",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 92953409,
		trips: 3,
		truck_no: 800,
	},
	{
		name: "Dominic Perez",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 90578081,
		trips: 4,
		truck_no: 809,
	},
	{
		name: "Ethan Richardson",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 95870813,
		trips: 3,
		truck_no: 109,
	},
	{
		name: "Fernando Stewart",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 91122678,
		trips: 3,
		truck_no: 799,
	},
	{
		name: "Gabriel Rivera",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 96408726,
		trips: 4,
		truck_no: 384,
	},
	{
		name: "Hector Hayes",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 94378928,
		trips: 4,
		truck_no: 425,
	},
	{
		name: "Ivan Turner",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 97622194,
		trips: 4,
		truck_no: 908,
	},
	{
		name: "Jacob Richardson",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 99845591,
		trips: 4,
		truck_no: 380,
	},
	{
		name: "Kyle Jenkins",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 93500677,
		trips: 4,
		truck_no: 902,
	},
	{
		name: "Liam Martinez",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 95064799,
		trips: 5,
		truck_no: 336,
	},
	{
		name: "Marcus Clark",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 90023226,
		trips: 3,
		truck_no: 720,
	},
	{
		name: "Nathan Wilson",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 99734630,
		trips: 4,
		truck_no: 919,
	},
	{
		name: "Oliver Edwards",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 91090118,
		trips: 3,
		truck_no: 936,
	},
	{
		name: "Parker Wright",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 95927415,
		trips: 3,
		truck_no: 509,
	},
	{
		name: "Quinn Foster",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 93814866,
		trips: 5,
		truck_no: 401,
	},
	{
		name: "Ricardo Collins",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 99392525,
		trips: 5,
		truck_no: 556,
	},
	{
		name: "Santiago Parker",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 99107367,
		trips: 3,
		truck_no: 780,
	},
	{
		name: "Theodore Jenkins",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 90019088,
		trips: 3,
		truck_no: 579,
	},
	{
		name: "Uriah Martinez",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 93623810,
		trips: 4,
		truck_no: 114,
	},
	{
		name: "Victor Turner",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 96269719,
		trips: 3,
		truck_no: 624,
	},
	{
		name: "Wesley Richardson",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 92533917,
		trips: 3,
		truck_no: 704,
	},
	{
		name: "Xavier Stewart",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 97646574,
		trips: 3,
		truck_no: 436,
	},
	{
		name: "Yahir Murphy",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 98889734,
		trips: 3,
		truck_no: 501,
	},
	{
		name: "Zachary Butler",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 94930853,
		trips: 3,
		truck_no: 994,
	},
	{
		name: "Aidan Perry",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 93753352,
		trips: 3,
		truck_no: 644,
	},
	{
		name: "Brandon Turner",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 93561819,
		trips: 3,
		truck_no: 389,
	},
	{
		name: "Caleb Watson",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 99548004,
		trips: 3,
		truck_no: 441,
	},
	{
		name: "Dominic Perez",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 90824775,
		trips: 4,
		truck_no: 664,
	},
	{
		name: "Ethan Richardson",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 94000879,
		trips: 4,
		truck_no: 595,
	},
	{
		name: "Fernando Stewart",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 91950251,
		trips: 5,
		truck_no: 383,
	},
	{
		name: "Gabriel Rivera",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 90829820,
		trips: 5,
		truck_no: 987,
	},
	{
		name: "Hector Hayes",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 95158072,
		trips: 4,
		truck_no: 145,
	},
	{
		name: "Ivan Turner",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 98785220,
		trips: 5,
		truck_no: 963,
	},
	{
		name: "Jacob Richardson",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 94156618,
		trips: 5,
		truck_no: 280,
	},
	{
		name: "Kyle Jenkins",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 90980658,
		trips: 5,
		truck_no: 288,
	},
	{
		name: "Liam Martinez",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 93626407,
		trips: 3,
		truck_no: 483,
	},
	{
		name: "Marcus Clark",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 98634884,
		trips: 4,
		truck_no: 989,
	},
	{
		name: "Nathan Wilson",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 94523069,
		trips: 4,
		truck_no: 172,
	},
	{
		name: "Oliver Edwards",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 97715133,
		trips: 5,
		truck_no: 673,
	},
	{
		name: "Parker Wright",
		active: "Active",
		zone: "West",
		status: "Ongoing Delivery",
		phone: 96477154,
		trips: 5,
		truck_no: 502,
	},
	{
		name: "Quinn Foster",
		active: "Inactive",
		zone: "North",
		status: "-",
		phone: 95628680,
		trips: 0,
		truck_no: 450,
	},
	{
		name: "Ricardo Collins",
		active: "Inactive",
		zone: "North",
		status: "-",
		phone: 91832646,
		trips: 0,
		truck_no: 864,
	},
	{
		name: "Santiago Parker",
		active: "Inactive",
		zone: "North",
		status: "-",
		phone: 97369123,
		trips: 0,
		truck_no: 917,
	},
	{
		name: "Theodore Jenkins",
		active: "Inactive",
		zone: "North",
		status: "-",
		phone: 97153616,
		trips: 0,
		truck_no: 937,
	},
	{
		name: "Uriah Martinez",
		active: "Inactive",
		zone: "North",
		status: "-",
		phone: 98729798,
		trips: 0,
		truck_no: 905,
	},
	{
		name: "Victor Turner",
		active: "Inactive",
		zone: "North",
		status: "-",
		phone: 94050874,
		trips: 0,
		truck_no: 600,
	},
	{
		name: "Wesley Richardson",
		active: "Inactive",
		zone: "North",
		status: "-",
		phone: 95539234,
		trips: 0,
		truck_no: 888,
	},
	{
		name: "Xavier Stewart",
		active: "Inactive",
		zone: "North",
		status: "-",
		phone: 98340027,
		trips: 0,
		truck_no: 724,
	},
	{
		name: "Yahir Murphy",
		active: "Inactive",
		zone: "North",
		status: "-",
		phone: 91920720,
		trips: 0,
		truck_no: 607,
	},
	{
		name: "Zachary Butler",
		active: "Inactive",
		zone: "North",
		status: "-",
		phone: 98571993,
		trips: 0,
		truck_no: 180,
	},
	{
		name: "Aidan Perry",
		active: "Inactive",
		zone: "North",
		status: "-",
		phone: 91963135,
		trips: 0,
		truck_no: 963,
	},
	{
		name: "Brandon Turner",
		active: "Inactive",
		zone: "North",
		status: "-",
		phone: 93438317,
		trips: 0,
		truck_no: 456,
	},
	{
		name: "Caleb Watson",
		active: "Inactive",
		zone: "North",
		status: "-",
		phone: 90535645,
		trips: 0,
		truck_no: 219,
	},
	{
		name: "Dominic Perez",
		active: "Inactive",
		zone: "North",
		status: "-",
		phone: 93675067,
		trips: 0,
		truck_no: 193,
	},
	{
		name: "Ethan Richardson",
		active: "Inactive",
		zone: "North",
		status: "-",
		phone: 99666908,
		trips: 0,
		truck_no: 900,
	},
	{
		name: "Fernando Stewart",
		active: "Inactive",
		zone: "North",
		status: "-",
		phone: 96954588,
		trips: 0,
		truck_no: 681,
	},
	{
		name: "Gabriel Rivera",
		active: "Inactive",
		zone: "North",
		status: "-",
		phone: 91712579,
		trips: 0,
		truck_no: 601,
	},
	{
		name: "Hector Hayes",
		active: "Inactive",
		zone: "North",
		status: "-",
		phone: 97657910,
		trips: 0,
		truck_no: 132,
	},
	{
		name: "Ivan Turner",
		active: "Inactive",
		zone: "South",
		status: "-",
		phone: 99712621,
		trips: 0,
		truck_no: 398,
	},
	{
		name: "Jacob Richardson",
		active: "Inactive",
		zone: "South",
		status: "-",
		phone: 96260010,
		trips: 0,
		truck_no: 696,
	},
	{
		name: "Kyle Jenkins",
		active: "Inactive",
		zone: "South",
		status: "-",
		phone: 97036270,
		trips: 0,
		truck_no: 225,
	},
	{
		name: "Liam Martinez",
		active: "Inactive",
		zone: "South",
		status: "-",
		phone: 92082058,
		trips: 0,
		truck_no: 557,
	},
	{
		name: "Marcus Clark",
		active: "Inactive",
		zone: "South",
		status: "-",
		phone: 91479713,
		trips: 0,
		truck_no: 129,
	},
	{
		name: "Nathan Wilson",
		active: "Inactive",
		zone: "South",
		status: "-",
		phone: 99340453,
		trips: 0,
		truck_no: 365,
	},
	{
		name: "Oliver Edwards",
		active: "Inactive",
		zone: "South",
		status: "-",
		phone: 92836107,
		trips: 0,
		truck_no: 798,
	},
	{
		name: "Parker Wright",
		active: "Inactive",
		zone: "South",
		status: "-",
		phone: 94761889,
		trips: 0,
		truck_no: 297,
	},
	{
		name: "Quinn Foster",
		active: "Inactive",
		zone: "South",
		status: "-",
		phone: 92886403,
		trips: 0,
		truck_no: 698,
	},
	{
		name: "Ricardo Collins",
		active: "Inactive",
		zone: "South",
		status: "-",
		phone: 90349811,
		trips: 0,
		truck_no: 587,
	},
	{
		name: "Santiago Parker",
		active: "Inactive",
		zone: "East",
		status: "-",
		phone: 98920896,
		trips: 0,
		truck_no: 471,
	},
	{
		name: "Theodore Jenkins",
		active: "Inactive",
		zone: "East",
		status: "-",
		phone: 91563746,
		trips: 0,
		truck_no: 624,
	},
	{
		name: "Uriah Martinez",
		active: "Inactive",
		zone: "East",
		status: "-",
		phone: 96159182,
		trips: 0,
		truck_no: 665,
	},
	{
		name: "Victor Turner",
		active: "Inactive",
		zone: "East",
		status: "-",
		phone: 92452716,
		trips: 0,
		truck_no: 200,
	},
	{
		name: "Wesley Richardson",
		active: "Inactive",
		zone: "East",
		status: "-",
		phone: 96253806,
		trips: 0,
		truck_no: 804,
	},
	{
		name: "Xavier Stewart",
		active: "Inactive",
		zone: "East",
		status: "-",
		phone: 97413046,
		trips: 0,
		truck_no: 514,
	},
	{
		name: "Yahir Murphy",
		active: "Inactive",
		zone: "East",
		status: "-",
		phone: 93250708,
		trips: 0,
		truck_no: 432,
	},
	{
		name: "Zachary Butler",
		active: "Inactive",
		zone: "East",
		status: "-",
		phone: 98976086,
		trips: 0,
		truck_no: 603,
	},
	{
		name: "Aidan Perry",
		active: "Inactive",
		zone: "East",
		status: "-",
		phone: 92120904,
		trips: 0,
		truck_no: 167,
	},
	{
		name: "Brandon Turner",
		active: "Inactive",
		zone: "East",
		status: "-",
		phone: 94120296,
		trips: 0,
		truck_no: 310,
	},
	{
		name: "Caleb Watson",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 93963957,
		trips: 0,
		truck_no: 823,
	},
	{
		name: "Dominic Perez",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 93819386,
		trips: 0,
		truck_no: 710,
	},
	{
		name: "Ethan Richardson",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 92127965,
		trips: 0,
		truck_no: 185,
	},
	{
		name: "Fernando Stewart",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 95330589,
		trips: 0,
		truck_no: 667,
	},
	{
		name: "Gabriel Rivera",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 99327435,
		trips: 0,
		truck_no: 164,
	},
	{
		name: "Hector Hayes",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 95222801,
		trips: 0,
		truck_no: 315,
	},
	{
		name: "Ivan Turner",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 90024742,
		trips: 0,
		truck_no: 550,
	},
	{
		name: "Jacob Richardson",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 97087156,
		trips: 0,
		truck_no: 841,
	},
	{
		name: "Kyle Jenkins",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 94653504,
		trips: 0,
		truck_no: 477,
	},
	{
		name: "Liam Martinez",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 96783431,
		trips: 0,
		truck_no: 733,
	},
	{
		name: "Marcus Clark",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 94562713,
		trips: 0,
		truck_no: 992,
	},
	{
		name: "Nathan Wilson",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 93609430,
		trips: 0,
		truck_no: 236,
	},
	{
		name: "Oliver Edwards",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 98844715,
		trips: 0,
		truck_no: 821,
	},
	{
		name: "Parker Wright",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 94388349,
		trips: 0,
		truck_no: 874,
	},
	{
		name: "Quinn Foster",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 98303783,
		trips: 0,
		truck_no: 684,
	},
	{
		name: "Ricardo Collins",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 93679767,
		trips: 0,
		truck_no: 979,
	},
	{
		name: "Santiago Parker",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 99461863,
		trips: 0,
		truck_no: 955,
	},
	{
		name: "Theodore Jenkins",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 99059443,
		trips: 0,
		truck_no: 797,
	},
	{
		name: "Uriah Martinez",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 99575637,
		trips: 0,
		truck_no: 775,
	},
	{
		name: "Victor Turner",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 93036294,
		trips: 0,
		truck_no: 525,
	},
	{
		name: "Wesley Richardson",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 99604492,
		trips: 0,
		truck_no: 689,
	},
	{
		name: "Xavier Stewart",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 96684607,
		trips: 0,
		truck_no: 458,
	},
	{
		name: "Yahir Murphy",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 93519082,
		trips: 0,
		truck_no: 518,
	},
	{
		name: "Zachary Butler",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 98953489,
		trips: 0,
		truck_no: 807,
	},
	{
		name: "Aidan Perry",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 92431655,
		trips: 0,
		truck_no: 715,
	},
	{
		name: "Brandon Turner",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 95462024,
		trips: 0,
		truck_no: 500,
	},
	{
		name: "Caleb Watson",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 97428253,
		trips: 0,
		truck_no: 332,
	},
	{
		name: "Dominic Perez",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 90302521,
		trips: 0,
		truck_no: 796,
	},
	{
		name: "Ethan Richardson",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 94183941,
		trips: 0,
		truck_no: 927,
	},
	{
		name: "Fernando Stewart",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 95646521,
		trips: 0,
		truck_no: 990,
	},
	{
		name: "Gabriel Rivera",
		active: "Inactive",
		zone: "West",
		status: "-",
		phone: 97521941,
		trips: 0,
		truck_no: 111,
	},
];
